//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class userinfo
    {
        [Required(ErrorMessage="用户名不能为空")]
        [StringLength(10,ErrorMessage="名字长度不能大于10")]
        public string userName { get; set; }

        [Required(ErrorMessage="年龄不能为空")]
        [Range(20, 29, ErrorMessage="年龄20-29")]
        public Nullable<int> age { get; set; }

        [DataType(DataType.EmailAddress,ErrorMessage="邮箱格式不正确")]
        public string email { get; set; }
        [Compare("identId", ErrorMessage = "两次密码输入需要一致")]
        public int identId { get; set; }

        [RegularExpression(@"^[1][358][0-9]{9}$",ErrorMessage="手机号格式错误")]
        public string tel { get; set; }
    }
}
